import { MigrationInterface, QueryRunner } from "typeorm";

export class CreatePasswordResetAndTokenTables1746825224702 implements MigrationInterface {
    name = 'CreatePasswordResetAndTokenTables1746825224702'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`faculty\` DROP FOREIGN KEY \`FK_008d2d8e1cfff7ed33b6c4029bf\``);
        await queryRunner.query(`ALTER TABLE \`faculty\` DROP FOREIGN KEY \`FK_8bfeeeb1ddee46f095f5181f8cc\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP FOREIGN KEY \`FK_2a7ac955ea573f8be71d736cef8\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP FOREIGN KEY \`FK_c14488f46704b1c5aacfb12d232\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP FOREIGN KEY \`FK_fb3eff90b11bddf7285f9b4e281\``);
        await queryRunner.query(`ALTER TABLE \`programs\` DROP FOREIGN KEY \`FK_95acfc8225a0719c2cfe7dcdac0\``);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP FOREIGN KEY \`FK_0665f6e2489bc805823ad4ea0a2\``);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` DROP FOREIGN KEY \`FK_bd2726fd31b35443f2245b93ba0\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_9a8a82462cab47c73d25f49261f\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_87b8888186ca9769c960e926870\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_b23c65e50a758245a33ee35fda1\``);
        await queryRunner.query(`DROP INDEX \`UQ_8bfeeeb1ddee46f095f5181f8cc\` ON \`faculty\``);
        await queryRunner.query(`DROP INDEX \`UQ_ae5a1f8e920b04e7ddf367114a9\` ON \`students\``);
        await queryRunner.query(`DROP INDEX \`UQ_11924ca2e0cb47a8d9400bada03\` ON \`programs\``);
        await queryRunner.query(`DROP INDEX \`UQ_91fddbe23e927e1e525c152baa3\` ON \`departments\``);
        await queryRunner.query(`DROP INDEX \`UQ_48ce552495d14eae9b187bb6716\` ON \`permissions\``);
        await queryRunner.query(`DROP INDEX \`UQ_648e3f5447f725579d7d4ffdfb7\` ON \`roles\``);
        await queryRunner.query(`DROP INDEX \`unique_user_role\` ON \`user_roles\``);
        await queryRunner.query(`DROP INDEX \`UQ_97672ac88f789774dd47f7c8be3\` ON \`users\``);
        await queryRunner.query(`CREATE TABLE \`studentsection\` (\`id\` int NOT NULL AUTO_INCREMENT, \`studentId\` int NOT NULL, \`sectionId\` int NOT NULL, \`enrollmentDate\` datetime NOT NULL, \`status\` enum ('active', 'inactive', 'suspended', 'deleted') NOT NULL DEFAULT 'active', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`course\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` varchar(255) NULL, \`creditHours\` int NOT NULL, \`status\` enum ('active', 'inactive', 'archived') NOT NULL DEFAULT 'active', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`departmentId\` int NOT NULL, \`labHours\` int NOT NULL, \`theoryHours\` int NOT NULL, \`type\` enum ('THEORY', 'LAB', 'PROJECT', 'THESIS') NOT NULL, UNIQUE INDEX \`IDX_5cf4963ae12285cda6432d5a3a\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`timetableslot\` (\`id\` int NOT NULL AUTO_INCREMENT, \`sectionId\` int NOT NULL, \`dayOfWeek\` int NOT NULL, \`startTime\` time NOT NULL, \`endTime\` time NOT NULL, \`roomNumber\` varchar(255) NULL, \`status\` enum ('active', 'inactive', 'suspended', 'deleted') NOT NULL DEFAULT 'active', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`section\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`courseId\` int NOT NULL, \`facultyId\` int NULL, \`semester\` int NOT NULL, \`maxStudents\` int NOT NULL, \`status\` enum ('active', 'inactive', 'suspended', 'deleted') NOT NULL DEFAULT 'active', \`startDate\` datetime NOT NULL, \`endDate\` datetime NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`session\` (\`id\` int NOT NULL AUTO_INCREMENT, \`sectionId\` int NOT NULL, \`date\` datetime NOT NULL, \`startTime\` datetime NOT NULL, \`endTime\` datetime NOT NULL, \`topic\` varchar(255) NULL, \`remarks\` varchar(255) NULL, \`status\` enum ('scheduled', 'in_progress', 'completed', 'cancelled', 'postponed') NOT NULL DEFAULT 'scheduled', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`attendance\` (\`id\` int NOT NULL AUTO_INCREMENT, \`studentSectionId\` int NOT NULL, \`sessionId\` int NOT NULL, \`status\` enum ('present', 'absent', 'late', 'leave', 'excused') NOT NULL, \`markedBy\` int NOT NULL, \`remarks\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`userId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`passwordreset\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, \`token\` varchar(255) NOT NULL, \`expiresAt\` datetime NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_3600de8d491efc5cfa99a43e01\` (\`token\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`passwordresettoken\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, \`token\` varchar(255) NOT NULL, \`expiresAt\` datetime NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`usersId\` int NULL, UNIQUE INDEX \`IDX_4ceb7f45b5d0ec5d068a5203a8\` (\`token\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`faculty\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`faculty\` DROP COLUMN \`department_id\``);
        await queryRunner.query(`ALTER TABLE \`faculty\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`faculty\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`roll_number\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`program_id\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`department_id\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`programs\` DROP COLUMN \`department_id\``);
        await queryRunner.query(`ALTER TABLE \`programs\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`programs\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP COLUMN \`admin_id\``);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` DROP COLUMN \`entity_type\``);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` DROP COLUMN \`entity_id\``);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` DROP COLUMN \`ip_address\``);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`is_read\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`permissions\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`permissions\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`permissions\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`permissions\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP COLUMN \`role_id\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`faculty\` ADD \`userId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`faculty\` ADD \`departmentId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`faculty\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`faculty\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`rollNumber\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD UNIQUE INDEX \`IDX_82b55075370818970f61b122fa\` (\`rollNumber\`)`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`userId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`departmentId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`programId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`programs\` ADD \`duration\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`programs\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`programs\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`programs\` ADD \`departmentId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`programs\` ADD \`totalCreditHours\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD \`adminId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` ADD \`entity\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` ADD \`entityId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` ADD \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`status\` enum ('unread', 'read') NOT NULL DEFAULT 'unread'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`link\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`permissions\` ADD \`resource\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`permissions\` ADD \`action\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`permissions\` ADD \`allowed\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`permissions\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`permissions\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`permissions\` ADD \`roleId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD \`roleId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`username\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_fe0bb3f6520ee0469504521e71\` (\`username\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`phone_number\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`profile_image\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`last_login\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`email_verified\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`faculty\` CHANGE \`status\` \`status\` enum ('active', 'inactive') NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`status\` \`status\` enum ('active', 'inactive') NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE \`programs\` DROP COLUMN \`code\``);
        await queryRunner.query(`ALTER TABLE \`programs\` ADD \`code\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`programs\` ADD UNIQUE INDEX \`IDX_11924ca2e0cb47a8d9400bada0\` (\`code\`)`);
        await queryRunner.query(`ALTER TABLE \`programs\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`programs\` ADD \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP COLUMN \`code\``);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD \`code\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD UNIQUE INDEX \`IDX_91fddbe23e927e1e525c152baa\` (\`code\`)`);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` DROP COLUMN \`action\``);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` ADD \`action\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` DROP COLUMN \`details\``);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` ADD \`details\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`message\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`message\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD UNIQUE INDEX \`IDX_648e3f5447f725579d7d4ffdfb\` (\`name\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`status\` \`status\` enum ('active', 'inactive') NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE \`faculty\` ADD CONSTRAINT \`FK_4058477ea808281336b4c55f5d2\` FOREIGN KEY (\`departmentId\`) REFERENCES \`departments\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`studentsection\` ADD CONSTRAINT \`FK_486d8cae6bb2b1a8c8505a6a63c\` FOREIGN KEY (\`sectionId\`) REFERENCES \`section\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`studentsection\` ADD CONSTRAINT \`FK_38b482f84274b31ec354a3437fa\` FOREIGN KEY (\`studentId\`) REFERENCES \`students\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD CONSTRAINT \`FK_492f4df328e3a1db2296576cf7f\` FOREIGN KEY (\`departmentId\`) REFERENCES \`departments\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD CONSTRAINT \`FK_00e43a3c44216514044bac1e675\` FOREIGN KEY (\`programId\`) REFERENCES \`programs\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`programs\` ADD CONSTRAINT \`FK_e8162ce37d0b6852083dce0f6fa\` FOREIGN KEY (\`departmentId\`) REFERENCES \`departments\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD CONSTRAINT \`FK_41a945d2820a7f2c9fef21091aa\` FOREIGN KEY (\`adminId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`course\` ADD CONSTRAINT \`FK_62bd85cf9a50b5dff651935e028\` FOREIGN KEY (\`departmentId\`) REFERENCES \`departments\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`timetableslot\` ADD CONSTRAINT \`FK_0c2973c4d7c1f0d3988e20e706b\` FOREIGN KEY (\`sectionId\`) REFERENCES \`section\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`section\` ADD CONSTRAINT \`FK_c61e35b7deed3caab17e821144a\` FOREIGN KEY (\`courseId\`) REFERENCES \`course\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`section\` ADD CONSTRAINT \`FK_652bb8e93bfc8677fe870a641fa\` FOREIGN KEY (\`facultyId\`) REFERENCES \`faculty\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`session\` ADD CONSTRAINT \`FK_253eac66e7d70b02f87de3c21f8\` FOREIGN KEY (\`sectionId\`) REFERENCES \`section\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attendance\` ADD CONSTRAINT \`FK_466e85b813d871bfb693f443528\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attendance\` ADD CONSTRAINT \`FK_4b3ed2a2a22881087475bc2e597\` FOREIGN KEY (\`sessionId\`) REFERENCES \`session\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attendance\` ADD CONSTRAINT \`FK_6631ecd27cb6205b8347882a6c4\` FOREIGN KEY (\`studentSectionId\`) REFERENCES \`studentsection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` ADD CONSTRAINT \`FK_cfa83f61e4d27a87fcae1e025ab\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_692a909ee0fa9383e7859f9b406\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`passwordreset\` ADD CONSTRAINT \`FK_d7e2662e9b4cdbdedd4241437ea\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`passwordresettoken\` ADD CONSTRAINT \`FK_4bf8f48b31b2962d89eba2eea46\` FOREIGN KEY (\`usersId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`permissions\` ADD CONSTRAINT \`FK_36d7b8e1a331102ec9161e879ce\` FOREIGN KEY (\`roleId\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_472b25323af01488f1f66a06b67\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_86033897c009fcca8b6505d6be2\` FOREIGN KEY (\`roleId\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_86033897c009fcca8b6505d6be2\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_472b25323af01488f1f66a06b67\``);
        await queryRunner.query(`ALTER TABLE \`permissions\` DROP FOREIGN KEY \`FK_36d7b8e1a331102ec9161e879ce\``);
        await queryRunner.query(`ALTER TABLE \`passwordresettoken\` DROP FOREIGN KEY \`FK_4bf8f48b31b2962d89eba2eea46\``);
        await queryRunner.query(`ALTER TABLE \`passwordreset\` DROP FOREIGN KEY \`FK_d7e2662e9b4cdbdedd4241437ea\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_692a909ee0fa9383e7859f9b406\``);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` DROP FOREIGN KEY \`FK_cfa83f61e4d27a87fcae1e025ab\``);
        await queryRunner.query(`ALTER TABLE \`attendance\` DROP FOREIGN KEY \`FK_6631ecd27cb6205b8347882a6c4\``);
        await queryRunner.query(`ALTER TABLE \`attendance\` DROP FOREIGN KEY \`FK_4b3ed2a2a22881087475bc2e597\``);
        await queryRunner.query(`ALTER TABLE \`attendance\` DROP FOREIGN KEY \`FK_466e85b813d871bfb693f443528\``);
        await queryRunner.query(`ALTER TABLE \`session\` DROP FOREIGN KEY \`FK_253eac66e7d70b02f87de3c21f8\``);
        await queryRunner.query(`ALTER TABLE \`section\` DROP FOREIGN KEY \`FK_652bb8e93bfc8677fe870a641fa\``);
        await queryRunner.query(`ALTER TABLE \`section\` DROP FOREIGN KEY \`FK_c61e35b7deed3caab17e821144a\``);
        await queryRunner.query(`ALTER TABLE \`timetableslot\` DROP FOREIGN KEY \`FK_0c2973c4d7c1f0d3988e20e706b\``);
        await queryRunner.query(`ALTER TABLE \`course\` DROP FOREIGN KEY \`FK_62bd85cf9a50b5dff651935e028\``);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP FOREIGN KEY \`FK_41a945d2820a7f2c9fef21091aa\``);
        await queryRunner.query(`ALTER TABLE \`programs\` DROP FOREIGN KEY \`FK_e8162ce37d0b6852083dce0f6fa\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP FOREIGN KEY \`FK_00e43a3c44216514044bac1e675\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP FOREIGN KEY \`FK_492f4df328e3a1db2296576cf7f\``);
        await queryRunner.query(`ALTER TABLE \`studentsection\` DROP FOREIGN KEY \`FK_38b482f84274b31ec354a3437fa\``);
        await queryRunner.query(`ALTER TABLE \`studentsection\` DROP FOREIGN KEY \`FK_486d8cae6bb2b1a8c8505a6a63c\``);
        await queryRunner.query(`ALTER TABLE \`faculty\` DROP FOREIGN KEY \`FK_4058477ea808281336b4c55f5d2\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`status\` \`status\` enum ('active', 'inactive', 'suspended') NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\``);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP INDEX \`IDX_648e3f5447f725579d7d4ffdfb\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`message\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`message\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` DROP COLUMN \`details\``);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` ADD \`details\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` DROP COLUMN \`action\``);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` ADD \`action\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP INDEX \`IDX_91fddbe23e927e1e525c152baa\``);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP COLUMN \`code\``);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD \`code\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`programs\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`programs\` ADD \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`programs\` DROP INDEX \`IDX_11924ca2e0cb47a8d9400bada0\``);
        await queryRunner.query(`ALTER TABLE \`programs\` DROP COLUMN \`code\``);
        await queryRunner.query(`ALTER TABLE \`programs\` ADD \`code\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`status\` \`status\` enum ('active', 'inactive', 'graduated', 'suspended') NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE \`faculty\` CHANGE \`status\` \`status\` enum ('active', 'inactive', 'on_leave') NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`email_verified\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`last_login\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`profile_image\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`phone_number\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_fe0bb3f6520ee0469504521e71\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`username\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP COLUMN \`roleId\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`permissions\` DROP COLUMN \`roleId\``);
        await queryRunner.query(`ALTER TABLE \`permissions\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`permissions\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`permissions\` DROP COLUMN \`allowed\``);
        await queryRunner.query(`ALTER TABLE \`permissions\` DROP COLUMN \`action\``);
        await queryRunner.query(`ALTER TABLE \`permissions\` DROP COLUMN \`resource\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`link\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` DROP COLUMN \`entityId\``);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` DROP COLUMN \`entity\``);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP COLUMN \`adminId\``);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`programs\` DROP COLUMN \`totalCreditHours\``);
        await queryRunner.query(`ALTER TABLE \`programs\` DROP COLUMN \`departmentId\``);
        await queryRunner.query(`ALTER TABLE \`programs\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`programs\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`programs\` DROP COLUMN \`duration\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`programId\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`departmentId\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP INDEX \`IDX_82b55075370818970f61b122fa\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`rollNumber\``);
        await queryRunner.query(`ALTER TABLE \`faculty\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`faculty\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`faculty\` DROP COLUMN \`departmentId\``);
        await queryRunner.query(`ALTER TABLE \`faculty\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD \`role_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD \`user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`permissions\` ADD \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`permissions\` ADD \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`permissions\` ADD \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`permissions\` ADD \`name\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`is_read\` tinyint(1) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` ADD \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` ADD \`ip_address\` varchar(45) NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` ADD \`entity_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` ADD \`entity_type\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` ADD \`user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD \`admin_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`programs\` ADD \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`programs\` ADD \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`programs\` ADD \`department_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`department_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`program_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`roll_number\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`faculty\` ADD \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`faculty\` ADD \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`faculty\` ADD \`department_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`faculty\` ADD \`user_id\` int NOT NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_4ceb7f45b5d0ec5d068a5203a8\` ON \`passwordresettoken\``);
        await queryRunner.query(`DROP TABLE \`passwordresettoken\``);
        await queryRunner.query(`DROP INDEX \`IDX_3600de8d491efc5cfa99a43e01\` ON \`passwordreset\``);
        await queryRunner.query(`DROP TABLE \`passwordreset\``);
        await queryRunner.query(`DROP TABLE \`attendance\``);
        await queryRunner.query(`DROP TABLE \`session\``);
        await queryRunner.query(`DROP TABLE \`section\``);
        await queryRunner.query(`DROP TABLE \`timetableslot\``);
        await queryRunner.query(`DROP INDEX \`IDX_5cf4963ae12285cda6432d5a3a\` ON \`course\``);
        await queryRunner.query(`DROP TABLE \`course\``);
        await queryRunner.query(`DROP TABLE \`studentsection\``);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_97672ac88f789774dd47f7c8be3\` ON \`users\` (\`email\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`unique_user_role\` ON \`user_roles\` (\`user_id\`, \`role_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_648e3f5447f725579d7d4ffdfb7\` ON \`roles\` (\`name\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_48ce552495d14eae9b187bb6716\` ON \`permissions\` (\`name\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_91fddbe23e927e1e525c152baa3\` ON \`departments\` (\`code\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_11924ca2e0cb47a8d9400bada03\` ON \`programs\` (\`code\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_ae5a1f8e920b04e7ddf367114a9\` ON \`students\` (\`roll_number\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_8bfeeeb1ddee46f095f5181f8cc\` ON \`faculty\` (\`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_b23c65e50a758245a33ee35fda1\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_87b8888186ca9769c960e926870\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_9a8a82462cab47c73d25f49261f\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` ADD CONSTRAINT \`FK_bd2726fd31b35443f2245b93ba0\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD CONSTRAINT \`FK_0665f6e2489bc805823ad4ea0a2\` FOREIGN KEY (\`admin_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`programs\` ADD CONSTRAINT \`FK_95acfc8225a0719c2cfe7dcdac0\` FOREIGN KEY (\`department_id\`) REFERENCES \`departments\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD CONSTRAINT \`FK_fb3eff90b11bddf7285f9b4e281\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD CONSTRAINT \`FK_c14488f46704b1c5aacfb12d232\` FOREIGN KEY (\`department_id\`) REFERENCES \`departments\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD CONSTRAINT \`FK_2a7ac955ea573f8be71d736cef8\` FOREIGN KEY (\`program_id\`) REFERENCES \`programs\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`faculty\` ADD CONSTRAINT \`FK_8bfeeeb1ddee46f095f5181f8cc\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`faculty\` ADD CONSTRAINT \`FK_008d2d8e1cfff7ed33b6c4029bf\` FOREIGN KEY (\`department_id\`) REFERENCES \`departments\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
