import '@/styles/globals.css';
import type { Metadata } from 'next';
import {
  PRODUCT_DESCRIPTION,
  PRODUCT_FULL_NAME,
  PRODUCT_NAME,
  PRODUCT_TAGLINE,
} from '@/constants/branding';

/**
 * Marketing site metadata.
 *
 * This read `title: 'Create Next App'` / `description: 'Generated by create
 * next app'` — the scaffold defaults, shipped on the public homepage. That is
 * the browser tab, the search result and the link preview for the one page
 * that sells the product.
 *
 * The root layout already sets sensible values; this group overrides them for
 * the marketing page specifically, and adds the Open Graph and Twitter cards
 * a shared link needs.
 */
export const metadata: Metadata = {
  title: PRODUCT_FULL_NAME,
  description: PRODUCT_DESCRIPTION,
  openGraph: {
    type: 'website',
    siteName: PRODUCT_NAME,
    title: PRODUCT_FULL_NAME,
    description: PRODUCT_DESCRIPTION,
  },
  twitter: {
    card: 'summary_large_image',
    title: PRODUCT_FULL_NAME,
    description: PRODUCT_DESCRIPTION,
  },
  keywords: [
    'OBE',
    'outcome-based education',
    'CLO attainment',
    'PLO attainment',
    'accreditation',
    'PEC',
    'HEC',
    'NCEAC',
    PRODUCT_TAGLINE,
  ],
};

export default function LandingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
